version:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: lyutikovav-netology-prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
     - 9090:9090
    volumes:
     - ./prometheus:/etc/prometheus
     - prometheus-data:/prometheus
    networks:
     - lyutikovav-my-netology-hw
    restart: always
  pushgateway:
    image: prom/pushgateway:latest
    container_name: lyutikovav-netology-pushgateway
    ports:
     - 9091:9091
    networks:
     - lyutikovav-my-netology-hw
    depends_on:
     - lyutikovav-netology-prometheus
    restart: unless-stopped
  grafana:
    image: grafana/grafana:latest
    container_name: lyutikovav-netology-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
    ports:
     - 80:3000
    volumes:
     - ./grafana:/etc/grafana
     - grafana-data:/var/lib/grafana
    networks:
     - lyutikovav-my-netology-hw
    depends_on:
     - lyutikovav-netology-prometheus
    restart: unless-stopped

volumes:
  prometheus-data:
  grafana-data:

networks:
  lyutikovav-my-netology-hw:
    driver: bridge
    ipam:
      config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

